name: CI/CD Pipeline with Grype

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  vulnerability_scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          # Remove existing Docker packages
          sudo apt-get remove -y docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc

          # Add Docker's official GPG key
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg

          # Add the Docker repository to Apt sources
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update

          # Install Docker
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          
          # Start and enable Docker service
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Install go
        run: |
          wget https://golang.org/dl/go1.21.5.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.21.5.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin

      - name: Install Cosign
        run: |
          go install github.com/sigstore/cosign/v2/cmd/cosign@latest

      - name: Install jq
        run: |
          sudo apt-get install -y jq

      - name: Install pymongo
        run: |
          sudo apt-get install -y python3-pip
          pip install pymongo

      - name: Run Python script to execute Grype and push to MongoDB
        run: python .github/scripts/run_grype_and_push_to_mongo.py
