name: CI/CD Pipeline with Grype

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: read # This is required for actions/checkout

jobs:
  image-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Uncomment and modify the Docker installation step if needed
      # - name: Install Docker
      #   run: |
      #     # Remove existing Docker packages
      #     sudo apt-get remove -y docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc
      #     
      #     # ... (rest of the Docker installation steps)

      - name: Install grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Install go
        run: |
          wget https://golang.org/dl/go1.21.5.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.21.5.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin

      - name: Install jq
        run: |
          sudo apt-get install -y jq

      - name: Install Cosign
        uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19
        with:
          cosign-version: v1.0.0  # Specify the desired version

      - name: Download SBOM
        run: |                  
          cosign download attestation \
          --predicate-type https://spdx.dev/Document \
          public.ecr.aws/t4s8c0c3/kubectl | jq -r .payload | base64 -d | jq > sbom-index.spdx.json

      - name: See the SBOM 
        run: |
          ls
          cat sbom-index.spdx.json  # Print the contents for debugging purposes

      - name: Install SPDX Tools
        run: |
          sudo apt-get install spdx-tools

      - name: Validate SBOM with SPDX Tools
        run: spdxvalidate sbom-index.spdx.json

      - name: Run Grype Scan
        run: grype -sbom-file sbom-index.spdx.json
